<?php
// @codingStandardsIgnoreFile
/**
 * @var $block \Due\Payments\Block\Info\Cc
 */
?>
<?php echo $block->escapeHtml($block->getMethod()->getTitle()) ?>
<br/>
<?php if ($_specificInfo = $block->getSpecificInformation()): ?>
    <table class="data-table admin__table-secondary">
        <?php foreach ($_specificInfo as $_label => $_value): ?>
            <tr>
                <th><?php echo $block->escapeHtml($_label) ?>:</th>
                <td><?php echo nl2br(implode("\n", $block->getValueAsArray($_value, true))); ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif; ?>
